export const genderOptions = [
  { label: "Female", value: "female" },
  { label: "Male", value: "male" },
  { label: "Gender less", value: "genderless" },
  { label: "Unknown", value: "unknown" },
];

export const statusOptions = [
  { label: "Alive", value: "alive" },
  { label: "Dead", value: "dead" },
  { label: "Unknown", value: "unknown" },
];

export const speciesOptions = [
  { label: "Alien", value: "alien" },
  { label: "Animal", value: "animal" },
  { label: "Cronenberg", value: "Cronenberg" },
  { label: "Disease", value: "disease" },
  { label: "Human", value: "human" },
  { label: "Humanoid", value: "humanoid" },
  { label: "Poopybutthole", value: "poopybutthole" },
  { label: "Mythological creature", value: "mythological creature" },
  { label: "Robot", value: "robot" },
  { label: "Unknown", value: "unknown" },
];

export const characterTypeOptions = [
  { label: "Alien", value: "alien" },
  { label: "Alphabetrian", value: "alphabetrian" },
  { label: "Bepisian", value: "bepisian" },
  { label: "Bird Person", value: "bird-person" },
  { label: "Boobloosian", value: "boobloosian" },
  { label: "Cat Person", value: "cat-person" },
  { label: "Changeformer", value: "changeformer" },
  { label: "Chud", value: "chud" },
  { label: "Cromulon", value: "cromulon" },
  { label: "Cronenberg", value: "cronenberg" },
  { label: "Cyborg", value: "cyborg" },
  { label: "Dog", value: "dog" },
  { label: "Drumbloxian", value: "drumbloxian" },
  { label: "Elephant Person", value: "elephant-person" },
  { label: "Fish-Person", value: "fish-person" },
  { label: "Flansian", value: "flansian" },
  { label: "Garblovian", value: "garblovian" },
  { label: "Gear Person", value: "gear-person" },
  { label: "Genetic experiment", value: "genetic experiment" },
  { label: "Giant", value: "giant" },
  { label: "Glorzo", value: "glorzo" },
  { label: "Greebybobe", value: "greebybobe" },
  { label: "Gromflomite", value: "gromflomite" },
  { label: "Grunglokian", value: "grunglokian" },
  { label: "Hivemind", value: "hivemind" },
  { label: "Human", value: "human" },
  { label: "Human with antennae", value: "human with antennae" },
  {
    label: "Human with ants in his eyes",
    value: "human with ants in his eyes",
  },
  { label: "Human with baby legs", value: "human with baby legs" },
  { label: "Human with giant head", value: "human with giant head" },
  { label: "Korblock", value: "Korblock" },
  { label: "Krootabulan", value: "krootabulan" },
  { label: "Lizard Person", value: "lizard" },
  { label: "Mega Gargantuan", value: "mega gargantuan" },
  { label: "Memory", value: "memory" },
  { label: "Mr. Meeseeks", value: "meeseeks" },
  { label: "Mytholog", value: "mytholog" },
  { label: "Numbericon", value: "numbericon" },
  { label: "Parasite", value: "parasite" },
  { label: "Plutonian", value: "plutonian" },
  { label: "Pripudlian", value: "pripudlian" },
  { label: "Robobro", value: "robobro" },
  { label: "Scrotian", value: "scrotian" },
  { label: "Self-aware arm", value: "self-aware arm" },
  { label: "Sentient ant colony", value: "sentient ant colony" },
  { label: "Shimshamian", value: "shimshamian" },
  { label: "Snake", value: "snake" },
  { label: "Stair Goblin", value: "stair goblin" },
  { label: "Superhuman", value: "superhuman" },
  { label: "Time Gop", value: "time gop" },
  { label: "Traflorkian", value: "traflorkian" },
  { label: "Trunk Person", value: "trunk-person" },
  { label: "Tumblorkian", value: "tumblorkian" },
  { label: "Turkey", value: "turkey" },
  { label: "Vampire", value: "vampire" },
  { label: "Zigerion", value: "zigerion" },
  { label: "Zombodian", value: "zombodian" },
];
